# Generated by Django 2.0 on 2017-12-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0002_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='storyID',
        ),
        migrations.AddField(
            model_name='container',
            name='comments',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='story',
            name='containerID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='stories_app.Container'),
        ),
    ]
