# Generated by Django 2.0 on 2017-12-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0004_auto_20171223_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='containerID',
            field=models.TextField(default='001'),
        ),
    ]
