# Generated by Django 2.0 on 2017-12-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0005_story_containerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='containerID',
            field=models.TextField(default='001', max_length=3),
        ),
    ]
