# Generated by Django 2.0 on 2017-12-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0006_auto_20171223_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='Storyrow1',
        ),
    ]
