# Generated by Django 2.0 on 2017-12-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0007_auto_20171223_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyrow1',
            name='containerID',
        ),
    ]
