# Generated by Django 2.0 on 2017-12-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories_app', '0008_remove_storyrow1_containerid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storyrow1',
            new_name='Story',
        ),
    ]
